### ISSUE TITLE
source ~/.zshrc 를 쉘 스크립트 내에 넣어서 실행시켜주세요~ 

### ISSUE THREAD

**Issue by contemplation-person** [veggie-garden/42_resetting#1]
귀찮은데,,,,, 흠,,,,, 내가 하긴 싫고,,, 흠

**Comment by veggie-garden** [comment]
오늘 업데이트 했습니다!

**Comment by veggie-garden** [comment]
해결한 줄 알았는데 해결이 안 되었습니다... issue #2 과 유사하니 #2 에서 해결하도록 하겠습니다. 이슈 리포트 감사합니다...
